"""empty message

Revision ID: a21e4edb720f
Revises: d05089c8a943
Create Date: 2023-02-01 14:48:11.895238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21e4edb720f'
down_revision = 'd05089c8a943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('item_rating',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.DECIMAL(precision=5, scale=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('item_rating',
               existing_type=sa.DECIMAL(precision=5, scale=1),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
