"""empty message

Revision ID: f3b234bde881
Revises: a21e4edb720f
Create Date: 2023-02-01 14:49:44.958483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b234bde881'
down_revision = 'a21e4edb720f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('item_rating',
               existing_type=sa.NUMERIC(precision=5, scale=1),
               type_=sa.DECIMAL(precision=1, scale=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('item_rating',
               existing_type=sa.DECIMAL(precision=1, scale=1),
               type_=sa.NUMERIC(precision=5, scale=1),
               existing_nullable=True)

    # ### end Alembic commands ###
